name: Release action

on:
  push:
    branches: [master, "action/*"]

jobs:
  dist:
    runs-on: ubuntu-20.04
    concurrency:
      group: action-release
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
        working-directory: gh-action

      - name: Build
        run: |
          node node_modules/.bin/tsc
          cp -r action.yml package*.json node_modules dist/
        working-directory: gh-action

      - name: Ship dist
        run: |
          set -e
          mv gh-action/dist /tmp/action-dist
          git fetch --all
          git checkout v0.2 || git checkout -b v0.2
          git rm -r .
          mv /tmp/action-dist/* .
          git add -A
          git -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.io" \
              commit --allow-empty \
              -m "Update action branch for ${{github.sha}}"
          git push -u origin v0.2
