name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - "8.2"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@main
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - run: curl https://getcomposer.org/installer | php
      - name: phpstan analyze
        run: composer lint
  test:
    name: unit tests
    needs: [phpstan]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - "8.2"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@main
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - run: curl https://getcomposer.org/installer | php
      - name: run unit tests
        run: composer test
  fmt:
    name: code style check
    needs: [phpstan]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - "8.2"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@main
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - run: curl https://getcomposer.org/installer | php
      - run: composer install && php vendor/bin/php-cs-fixer fix --dry-run --diff
