name: Draft release

on:
  push:
    tags: "*"

jobs:
  draft:
    name: Create GitHub draft release
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@main
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - run: curl https://getcomposer.org/installer | php
      - name: Build artifact
        run: composer build
      - name: Compute tag
        id: compute-tag
        run: |
          tag=$(echo ${{github.ref}} | cut -d/ -f3)
          echo ::set-output name=TAG::$tag
          echo ::set-output name=BODY::$(git tag -l --format='%(contents)' $tag)
      - name: Create draft release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ github.workspace }}/pharynx.phar,plugin-dev/*
          commit: ${{ github.sha }}
          draft: true
          name: Version ${{ steps.compute-tag.outputs.TAG }}
          tag: ${{ steps.compute-tag.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.compute-tag.outputs.BODY }}
